-- Hall of Fame: campeões e vices calculados dos scores
-- Execute no Supabase SQL Editor

INSERT INTO hall_of_fame (season_number, champion, runner_up) VALUES
  (1, 'Ulisses', 'Neudson'),
  (2, 'Neudson', 'Denis'),
  (3, 'Edson', 'Neudson'),
  (4, 'Rodrigo', 'Edson'),
  (5, 'Peixe', 'Marcel'),
  (6, 'Fernando', 'Edson'),
  (7, 'Bougleux', 'Denis'),
  (8, 'Edson', 'Neudson'),
  (9, 'Neudson', 'Biro'),
  (10, 'Ganso', 'Cristiano'),
  (11, 'Rodrigo', 'Edson'),
  (12, 'Rodrigo', 'Edson'),
  (13, 'Edson', 'Teteco'),
  (14, 'Teteco', 'Rodrigo'),
  (15, 'David', 'Neudson'),
  (16, 'Cristiano', 'Rodrigo'),
  (17, 'David', 'Rafael'),
  (18, 'David', 'Rodrigo'),
  (19, 'Cristiano', 'David'),
  (20, 'Rafael', 'Teteco'),
  (21, 'Takeshi', 'Rafael'),
  (22, 'Teteco', 'Pedro'),
  (23, 'Rodrigo', 'Marcel'),
  (24, 'Pedro', 'Rafael'),
  (25, 'Cristiano', 'Rafael'),
  (26, 'Cristiano', 'Rafael'),
  (27, 'Pedro', 'Marcão'),
  (28, 'Rodrigo', 'Bruno Eduardo'),
  (29, 'Cristian', 'Léo'),
  (30, 'Rafael', 'Naibi'),
  (31, 'Marcel', 'Pedro'),
  (32, 'Rodrigo', 'Naibi'),
  (33, 'Carlos Henrique', 'Edson'),
  (34, 'Léo', 'Rafael'),
  (35, 'Léo', 'Carlos Henrique'),
  (36, 'Rafael', 'Léo'),
  (37, 'Rafael', 'Ricardo'),
  (38, 'Carlos Henrique', 'Rafael'),
  (39, 'Léo', 'Marcão'),
  (40, 'Rafael', 'Pedro'),
  (41, 'Rafael', 'Marcel'),
  (42, 'Léo', 'Rafael'),
  (43, 'Bruno Eduardo', 'Pedro Guedes'),
  (44, 'Rafael', 'Adilson'),
  (45, 'Teteco', 'Magossi'),
  (46, 'Carlos Henrique', 'Ricardo'),
  (47, 'Teteco', 'Naibi'),
  (48, 'Marcel', 'Edson'),
  (49, 'Douglas', 'Léo'),
  (50, 'Guilherme', 'Rafael'),
  (51, 'Rafael', 'Carlos Henrique'),
  (52, 'Guilherme', 'Teteco'),
  (53, 'Rafael', 'Magossi'),
  (54, 'Edson', 'Teteco'),
  (55, 'Teteco', 'Carlos Henrique'),
  (56, 'Carlos Henrique', 'Rafael'),
  (57, 'Rodrigo', 'Carlos Henrique'),
  (58, 'Rafael', 'Teteco'),
  (59, 'Rafael', 'Magossi'),
  (60, 'Rodrigo', 'Adilson'),
  (61, 'Teteco', 'Renato'),
  (62, 'Valmir', 'Teteco'),
  (63, 'Rafael', 'Luiz Vinicius'),
  (64, 'Teteco', 'Rodrigo'),
  (65, 'Teteco', 'Daniel Henrique'),
  (66, 'Rodrigo', 'Teteco'),
  (67, 'Rafael', 'Cristiano'),
  (68, 'Teteco', 'Sergio Fernandes'),
  (69, 'Rafael', 'Ricardo'),
  (70, 'Rafael', 'Rodrigo')
ON CONFLICT (season_number) DO UPDATE SET
  champion  = EXCLUDED.champion,
  runner_up = EXCLUDED.runner_up;

-- Total: 70 temporadas
